build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related qa APIs "
  contactDetails:
    name: "John deer - architect"
    email: "deer@eazybank.com"
  onCallSupport:
    - (555) 555-5432
    - (555) 523-3214
